---
- hosts: all
  vars:
    user_name: api
    pahkat_repo: pahkat_repo

  tasks:
  - name: Install Docker prerequisites
    become: true
    apt:
      update_cache: true
      name:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - lsb-release

  - name: Install Docker's GPG key
    become: true
    shell:
      cmd: >-
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg |
        gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
      creates: /usr/share/keyrings/docker-archive-keyring.gpg

  - name: Set up the Docker repository
    become: true
    shell:
      cmd: >-
        echo
        "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg]
        https://download.docker.com/linux/ubuntu
        $(lsb_release -cs) stable" |
        tee /etc/apt/sources.list.d/docker.list > /dev/null
      creates: /etc/apt/sources.list.d/docker.list

  - name: Install Docker
    become: true
    apt:
      update_cache: true
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - haveged

  - name: Pin the version of containerd.io
    become: true
    copy:
      src: pinfile
      dest: /etc/apt/preferences.d/pin-containerd
      mode: 0744

  - name: Install docker-compose
    become: true
    shell:
      cmd: >-
        curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)"
        -o /usr/local/bin/docker-compose
      creates: /usr/local/bin/docker-compose

  - name: Make docker-compose executable
    become: true
    file:
      path: /usr/local/bin/docker-compose
      mode: "+x"

  - name: Link docker-compose into /usr/bin
    become: true
    file:
      path: /usr/bin/docker-compose
      src: /usr/local/bin/docker-compose
      state: link

  - name: Ensure Docker service is started and enabled
    become: true
    service:
      name: docker.service
      enabled: true
      state: started

  - name: Create a Docker usergroup
    become: true
    group:
      name: docker
      state: present

  - name: Create {{ user_name }} user
    become: true
    user:
      name: "{{ user_name }}"
      append: true
      groups: docker

  - name: Create distribution directory
    become: true
    file:
      owner: "{{ user_name }}"
      group: "{{ user_name }}"
      mode: 0755
      state: directory
      path: /home/{{ user_name }}/dist

  - name: Ensure the distribution archive is ready
    file:
      path: dist.tar.gz
      state: file
    delegate_to: localhost

  - name: Deploy the dist
    become: true
    unarchive:
      src: dist.tar.gz
      dest: /home/{{ user_name }}/dist
      owner: "{{ user_name }}"

  - name: Install the dist
    become: true
    args:
      executable: /bin/bash
    shell: |
      set -euxo pipefail
      echo $PWD
      cd /home/{{ user_name }}/dist
      gunzip -c divvun-api.tar.gz | docker image load
      mkdir -p data/grammar
      mkdir -p data/spelling
      mkdir -p data/hyphenation
      chown -R {{ user_name }}:{{ user_name }} .

  - name: Create Caddyfile
    become: true
    template:
      src: Caddyfile.j2
      dest: /home/{{ user_name }}/dist/Caddyfile
      owner: "{{ user_name }}"
      group: "{{ user_name }}"
      mode: 0644

  - name: Run container
    become: True
    shell:
      cmd: "docker-compose up -d --remove-orphans"
      chdir: /home/{{ user_name }}/dist

  - name: Install Pahkat
    become: true
    args:
      executable: /bin/bash
    shell: |
      set -euxo pipefail
      cd /home/{{ user_name }}/dist
      PAHKAT_ARCHIVE=pahkat-prefix-cli_2.1.1_linux_x86_64.txz
      wget -O "$PAHKAT_ARCHIVE" https://divvun.ams3.cdn.digitaloceanspaces.com/pahkat/artifacts/"$PAHKAT_ARCHIVE" 
      tar xvf "$PAHKAT_ARCHIVE"
      mv bin/pahkat-prefix .
      rm -r bin

  - name: Setup Pahkat
    become: true
    args:
      executable: /bin/bash
    shell: |
      set -euxo pipefail
      cd /home/{{ user_name }}/dist
      ./pahkat-prefix init -c {{ pahkat_repo }}
      ./pahkat-prefix config repo add https://pahkat.uit.no/main -c {{ pahkat_repo }}

  - name: Install language files via Pahkat
    become: true
    args:
      executable: /bin/bash
    shell: |
      set -euxo pipefail
      cd /home/{{ user_name }}/dist
      ./pahkat-prefix download speller-sme -c {{ pahkat_repo }} # WIP: this needs re-working when pahkat supports downloading .zhfst files directly


  - name: Create cron job to update language files nightly
    cron:
      name: "Update language files"
      job: "cd /home/{{ user_name }}/dist/scripts && ./update_data.sh"
      hour: "3"
      minute: "0"